FROM ruby:2.6.3

RUN apt-get update && apt-get install apt-transport-https
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update -qq && apt-get install -y nodejs yarn


# Set an environment variable where the Rails app is installed to inside of Docker image
ENV RAILS_ROOT /var/www/curatingbits

RUN mkdir -p $RAILS_ROOT

# Set working directory
WORKDIR $RAILS_ROOT

# Setting env up
ENV RAILS_ENV='production'
ENV BUNDLE_PATH /bundle

COPY package.json yarn.lock ./
RUN yarn install --production

# Adding gems
COPY Gemfile Gemfile
COPY Gemfile.lock Gemfile.lock
RUN gem install bundler:2.0.1
RUN bundle install --jobs 20 --retry 5 --without development test

# Adding project files
COPY . /var/www/curatingbits

RUN bundle exec rake assets:clobber
RUN bundle exec rake assets:precompile



EXPOSE 3000
CMD ["bundle", "exec", "puma", "-C", "config/puma.rb"]
